schema: ./app/schema.graphql
extensions:
    endpoints:
        default:
            url: "http://localhost:8888/graphql"
            headers:
                {
                    "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpZ2sxOUBtZS5jb20iLCJleHAiOjE3NDM3MDU2MTAsInVzZXIiOnsiaWQiOiI2N2VjMDlmYWVhNWZmYTQyNjAzMDA1ODkiLCJjcmVhdGVkX2F0IjoiMjAyNS0wNC0wMSAxNTo0NDo1OC43MzMwMDAiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wNC0wMyAxODowMDoxMC44NjU1NjYiLCJlbWFpbCI6ImlnazE5QG1lLmNvbSIsInBob25lIjoiKzEtXHUyMDJhNTAzNzY1NTY4NFx1MjAyYyIsImZpcnN0X25hbWUiOiJJZ29yIiwibGFzdF9uYW1lIjoiS3VsZWJ5YWtpbiIsImlwIjoiMTcyLjE5LjAuMSIsImxhc3RfbG9nZ2VkX2F0IjoiMjAyNS0wNC0wMyAxODowMDoxMC44NjEwMDAifX0.pHLW68Vcht1oF4dzYPLbjKYHsvn45ys4tZ0XSx6ATW0",
                }
