schema: ./app/schema.graphql
extensions:
    endpoints:
        default:
            url: "http://localhost:8888/graphql"
            headers:
                {
                    "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpZ2sxOUBtZS5jb20iLCJleHAiOjE3NDMyMDIyODUsInVzZXIiOnsiaWQiOiI2N2U2Y2JlZDY1NTMxMDRkZWUzMDA1ODkiLCJjcmVhdGVkX2F0IjoiMjAyNS0wMy0yOCAxNjoxODo1My43MDMwMDAiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wMy0yOCAyMjoxMToyNS41ODY1NzciLCJlbWFpbCI6ImlnazE5QG1lLmNvbSIsInBob25lIjoiKzEtXHUyMDJhNTAzNzY1NTY4NFx1MjAyYyIsImZpcnN0X25hbWUiOiJJZ29yIiwibGFzdF9uYW1lIjoiS3VsZWJ5YWtpbiIsImlwIjoiMTcyLjE4LjAuMSIsImxhc3RfbG9nZ2VkX2F0IjoiMjAyNS0wMy0yOCAyMjoxMToyNS41ODEwMDAifX0.inPM7bGO22t8WVk4CeWNwP_1yG7NwaQQwS6f6rjFilc",
                }
